language: java

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "krishna192168"
    token:
      secure: 3e22e8dd6c74fc4eb2510a3dd4c7268e1405ae54 # sonor encrypted token
      
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  # here builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - ./gradlew build --scan -s
  
notifications:
  email:
    - krishnamoorthy.bavanudoss@revature.com
    - ragavanpv@revature.com
